# Generated by Django 3.2.5 on 2021-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('SAP_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DEPARTMENT', models.CharField(max_length=100)),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('MIDDLE_NAME', models.FileField(upload_to='papers/pdfs/')),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('ROLE', models.CharField(max_length=100)),
                ('DATE_OF_JOINING', models.DateField()),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
