# Generated by Django 3.2.5 on 2021-12-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='PUBLISHER',
        ),
    ]
