# Generated by Django 3.2.5 on 2021-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0002_alter_publisher_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='MIDDLE_NAME',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
