# Generated by Django 3.2.5 on 2021-12-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0003_alter_publisher_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('ISSUEP_ID', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('CATEGORY', models.CharField(max_length=20)),
                ('DESC', models.CharField(max_length=150)),
                ('RESPONSE', models.CharField(max_length=60)),
                ('ISSUE_STATUS', models.CharField(max_length=20)),
                ('TIME_S', models.DateTimeField()),
                ('PUB_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userview.publisher')),
            ],
            options={
                'db_table': 'ISSUE',
            },
        ),
    ]

