# Generated by Django 3.2.5 on 2021-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0005_auto_20211212_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ISSUEP_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
