# Generated by Django 3.2.5 on 2021-12-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0006_alter_issue_issuep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='papers',
        ),
    ]
