# Generated by Django 3.2.5 on 2021-12-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0010_remove_papers_papers'),
        ('Userview', '0007_remove_publisher_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='paper',
            field=models.ManyToManyField(to='upload_publication.Papers'),
        ),
    ]
