
# Generated by Django 3.2.5 on 2021-12-14 14:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0009_area_of_interest_pub_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='MIDDLE_NAME',

            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
