# Generated by Django 3.2.5 on 2021-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0010_alter_publisher_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='MIDDLE_NAME',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
