# Generated by Django 3.2.5 on 2021-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0011_alter_publisher_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='PHONE_NUMBER',
            field=models.IntegerField(max_length=10),
        ),
    ]
