# Generated by Django 3.2.5 on 2021-12-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0012_alter_publisher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='PHONE_NUMBER',
            field=models.CharField(max_length=10),
        ),
    ]
