# Generated by Django 3.2.5 on 2021-12-19 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0014_alter_publisher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ISSUE_STATUS',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='RESPONSE',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='issue',
            name='TIME_S',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
