# Generated by Django 3.2.5 on 2021-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0015_auto_20211219_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ISSUE_STATUS',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='RESPONSE',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
