# Generated by Django 3.2.5 on 2021-12-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0016_auto_20211219_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='DESC',
            field=models.CharField(max_length=250),
        ),
    ]
