# Generated by Django 3.2.5 on 2021-12-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_id', models.DecimalField(decimal_places=1, max_digits=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='papers/pdfs/')),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('ISSN', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ISSUE', models.CharField(max_length=50)),
                ('MONTH', models.CharField(max_length=10)),
                ('PUB_YEAR', models.IntegerField(max_length=4)),
                ('PGNO', models.IntegerField(verbose_name=5)),
                ('VOL', models.IntegerField(max_length=10)),
                ('LVL', models.CharField(max_length=15)),
                ('ISSN_TYPE', models.CharField(max_length=10)),
                ('PUB_TYPE', models.CharField(max_length=15)),
                ('NAME', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'REFERENCE',
            },
        ),
        migrations.CreateModel(
            name='Paper_Has_References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_publication.reference')),
                ('PAPER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_publication.papers')),
            ],
            options={
                'db_table': 'PAPER_HAS_REFERENCES',
                'unique_together': {('PAPER_ID', 'ISSN')},
            },
        ),
    ]
