# Generated by Django 3.2.5 on 2021-12-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0002_auto_20211212_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper_has_references',
            old_name='ISSN',
            new_name='ISSN_ID',
        ),
        migrations.RenameField(
            model_name='paper_has_references',
            old_name='PAPER_ID',
            new_name='P_ID',
        ),
        migrations.AlterUniqueTogether(
            name='paper_has_references',
            unique_together={('P_ID', 'ISSN_ID')},
        ),
    ]
