# Generated by Django 3.2.5 on 2021-12-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0005_alter_paper_has_references_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paper_has_references',
            unique_together=set(),
        ),
    ]
