# Generated by Django 3.2.5 on 2021-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0007_delete_paper_has_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
