# Generated by Django 3.2.5 on 2021-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userview', '0007_remove_publisher_papers'),
        ('upload_publication', '0008_alter_papers_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='papers',
            field=models.ManyToManyField(to='Userview.Publisher'),
        ),
    ]
