# Generated by Django 3.2.5 on 2021-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0011_auto_20211212_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='SCOPUS_INDEX',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='WEB_OF_SCIENCE',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='pdf',
            field=models.FileField(blank=True, upload_to='papers/pdfs/'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ISSUE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='PGNO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='VOL',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
