# Generated by Django 3.2.5 on 2021-12-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0014_auto_20211227_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='PGNO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='VOL',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
