# Generated by Django 3.2.5 on 2021-12-27 16:19

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0015_auto_20211227_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='SCOPUS_INDEX',
            field=models.CharField(blank=True, default=django.db.models.fields.NullBooleanField, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='WEB_OF_SCIENCE',
            field=models.CharField(blank=True, default=django.db.models.fields.NullBooleanField, max_length=50, null=True),
        ),
    ]
