# Generated by Django 3.2.5 on 2021-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0016_auto_20211227_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='MONTH',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reference',
            name='PGNO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='SCOPUS_INDEX',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='VOL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='WEB_OF_SCIENCE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
